name: ubuntu-24.04

on: workflow_dispatch

permissions:
  contents: read

jobs:
  demo:
    timeout-minutes: 1
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - run: pipx --version
